### PR TITLE
Config as derive

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This patchset changes the implementation of the config file parsing to use serde and serde_derive.

Benefits and Compromises are listed in the patch. Some adjustments had to be made to the tests, but I guess this results in feature parity (not sure with the one patch that changes the config key name from (for example) `shell =` to `command =`...).

Not tested in reallife env, only via `cargo test`.

### CODE REVIEW

**Comment by mario-kr** [comment]
With this patch, the configuration syntax will no longer work:  
example config (representative of how it was used before):
```toml
[general]
shell = "/usr/bin/bash"
output = "/dev"
[[items]]
key = "stdout"
interval = 10
file = "/proc/loadavg"
```
command + output:
```shell
> cargo run -- -c ../aktest.toml
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/antikoerper -c ../aktest.toml`
Error at loading config file (../aktest.toml):
missing field `command` for key `items`
```

It works when using `command` instead of `file`; But you do lose some verbosity in the configuration.

I personally don't like calling it command; maybe keep the (serde default) external tag of an enum, and configure it like
```toml
[[items]]
key = "stdout"
interval = 10
input.file = "/proc/loadavg"
# input.command = [ "df", "-sm" ]
# input.shell = "free | grep -e Mem:"
```

Also, there were three ways to define a command before, I don't know if that is still the case with `serde_derive` (no tests are covering this):
```
# shamelessly copied from the README.md
command = {path = "acpi", args = ["-v"]}
command = ["acpi", "-v"]
command = "acpi"
```
I also cannot really wrap my head around on what serde expects `ItemKind::Command(PathBuf, Vec<String>)` to look like in the toml-file.

**Comment by mario-kr** [comment]
OK, doing it via a tagged enum doesn't work for me; I'm utterly unable to provide a toml file which is satisfactory for the parser. toml doesn't support enums, and serializing enums is not possible via serde, so i can't check on how it's supposed to look like.  
I'm still kinda worried on how/if serde will differentiate between `File(PathBuf)` and `Shell(String)` - which might become important with entries like `command = "/bin/acpi"`. If it (antikoerper) tries to read the file instead of executing it in the shell (or as a single command), there will be an excessive amount of binary garbage in the output.

**Comment by matthiasbeyer** [comment]
> With this patch, the configuration syntax will no longer work:

That's intended because

> It works when using `command` instead of `file`

Which is what the README says how it _should_ work. The implementation before did not use `command` as key, though, but `file`/`shell`/etc. That was either false implementation or false documentation (or I misunderstood something).

> Also, there were three ways to define a command before, I don't know if that is still the case with `serde_derive` (no tests are covering this):
> 
> ```
> # shamelessly copied from the README.md
> command = {path = "acpi", args = ["-v"]}
> command = ["acpi", "-v"]
> command = "acpi"
> ```

The patch changed the implementation to match the (above) documentation (from my POV).

> I'm still kinda worried on how/if serde will differentiate between File(PathBuf) and Shell(String) - which might become important with entries like command = "/bin/acpi".
> If it (antikoerper) tries to read the file instead of executing it in the shell (or as a single command), there will be an excessive amount of binary garbage in the output.

This is true.
That's exactly how it should work now.

**Comment by TheNeikos** [comment]
You can use enums in toml: https://serde.rs/enum-representations.html

**Comment by mario-kr** [comment]
I just checked, and with `command = "/usr/bin/df"` nothing at all happens.
So this patch is basically breaking functionality :/

Also yes, there seems to be a misunderstanding regarding "command". Personally, I never ended up using it, but it basically allowed you to configure processes `exec*` style, whose output would be read and used.

@TheNeikos Nearly all examples in the serde docs are json; The only enum that worked for me was the untagged one, and the adjacently tagged one should work too; but not the default externally tagged enum. I also couldn't find working examples on the net.
IMO, an externally tagged enum would be in this case `command.file = "/proc/loadavg"` or `command.shell` or `command.command`

**Comment by TheNeikos** [comment]
You can see an example here: https://github.com/TheNeikos/rustdock/blob/master/src/config.rs

This parses files like this:

```
[[elements]]                                                                                             
type = "Command"                                                                                         
command = "~/bin/dock/herbstluft-tabs.sh"                                                                
                                                                                                       
[[elements]]                                                                                             
type = "Seperator"                                                                                       
sep = " | " 
```

**Comment by mario-kr** [comment]
yeah, i forgot to adjust the tests when making the changes. @matthiasbeyer could you do that, please? I won't get to it until next WE.

**Comment by matthiasbeyer** [comment]
Sure.

**Pull request closed without merging**
